class AppLocalizations {
  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'title_hexa_match': 'HEXA MATCH',
      'subtitle_neon': 'VIBRANT NEON 3-IN-A-ROW',
      'btn_start_game': 'START GAME',
      'menu_subtitle': 'SELECT YOUR CHALLENGE',
      'card_play_campaign': 'PLAY LEVEL {level}',
      'hud_level_title': 'LEVEL {level}',
      'card_campaign_sub': 'Campaign progress saved on device',
      'card_daily_event': 'DAILY EVENT',
      'card_daily_sub': 'Unique layout shape • Updates daily',
      'badge_completed': 'COMPLETED',
      'badge_new_challenge': 'NEW CHALLENGE',
      'panel_stats': 'YOUR STATS',
      'stat_best_score': 'BEST SCORE',
      'stat_levels_cleared': 'LEVELS CLEARED',
      'hud_score': 'Score: {score}',
      'hud_targets': 'Targets: {targets}',
      'badge_difficulty_easy': 'Easy',
      'badge_difficulty_normal': 'Normal',
      'badge_difficulty_medium': 'Medium',
      'badge_difficulty_hard': 'Hard',
      'badge_difficulty_very_hard': 'Very Hard',
      'overlay_game_over': 'GAME OVER',
      'overlay_game_over_sub': 'The hexagonal field is fully occupied.',
      'stat_final_score': 'FINAL SCORE',
      'stat_current_score': 'CURRENT SCORE',
      'btn_play_again': 'PLAY AGAIN',
      'btn_retry': 'RETRY',
      'overlay_victory': 'LEVEL COMPLETED!',
      'overlay_victory_congrats': 'Congratulations! All target items matched.',
      'overlay_victory_daily': 'EVENT COMPLETE!',
      'overlay_victory_daily_congrats': 'You have completed today\'s special challenge!',
      'btn_next_level': 'NEXT LEVEL',
      'btn_main_menu': 'MAIN MENU',
      'settings_title': 'SETTINGS',
      'settings_language': 'SELECT LANGUAGE',
      'settings_reset': 'RESET CAMPAIGN PROGRESS',
      'settings_close': 'CLOSE',
      'settings_reset_confirm': 'Progress Reset',
      'queue_next_up': 'NEXT UP',
      'queue_tap_to_swap': 'NEXT UP • TAP TO SWAP',
      'tutorial_step1_title': 'TUTORIAL: MATCHING',
      'tutorial_step1_msg': 'Tap the center cell to place the Red sphere. Connect 3 in a line to make a match!',
      'tutorial_step2_title': 'TUTORIAL: QUEUE SWAP',
      'tutorial_step2_msg': 'To match the Green target, you need a Green sphere. Tap the Green sphere in the queue below to swap it to the front!',
      'tutorial_step3_title': 'TUTORIAL: LAST TARGET',
      'tutorial_step3_msg': 'Great! Now tap the center cell to place the Green sphere and complete the level.',
      'tutorial_l5_step1_title': 'TUTORIAL: BOMB SPAWN',
      'tutorial_l5_step1_msg': 'Connect 4 items at once to create a bomb. Tap the highlighted cell to place the Red sphere!',
      'tutorial_l5_step2_title': 'TUTORIAL: BOMB DETONATION',
      'tutorial_l5_step2_msg': 'To trigger the bomb, clear any adjacent color. Tap the highlighted cell to place the Blue sphere and detonate the bomb!',
      'hud_daily_sub': 'Clear all 4 target stars on today\'s board',
      'hud_campaign_sub': 'Clear all target stars to advance',
    },
    'de': {
      'title_hexa_match': 'HEXA MATCH',
      'subtitle_neon': 'LEUCHTENDES NEON-3-GEWINNT',
      'btn_start_game': 'SPIEL STARTEN',
      'menu_subtitle': 'WÄHLE DEINE HERAUSFORDERUNG',
      'card_play_campaign': 'LEVEL {level} SPIELEN',
      'hud_level_title': 'LEVEL {level}',
      'card_campaign_sub': 'Kampagnenfortschritt auf dem Gerät gespeichert',
      'card_daily_event': 'TÄGLICHES EVENT',
      'card_daily_sub': 'Einzigartige Layout-Form • Täglich neu',
      'badge_completed': 'ABGESCHLOSSEN',
      'badge_new_challenge': 'NEUE AUFGABE',
      'panel_stats': 'DEINE STATISTIKEN',
      'stat_best_score': 'REKORD',
      'stat_levels_cleared': 'LEVELS GESCHAFFT',
      'hud_score': 'Punkte: {score}',
      'hud_targets': 'Ziele: {targets}',
      'badge_difficulty_easy': 'Einfach',
      'badge_difficulty_normal': 'Normal',
      'badge_difficulty_medium': 'Mittel',
      'badge_difficulty_hard': 'Schwer',
      'badge_difficulty_very_hard': 'Sehr Schwer',
      'overlay_game_over': 'SPIEL VORBEI',
      'overlay_game_over_sub': 'Das sechseckige Spielfeld ist vollständig besetzt.',
      'stat_final_score': 'ENDPUNKTE',
      'stat_current_score': 'AKTUELLE PUNKTE',
      'btn_play_again': 'NOCHMAL SPIELEN',
      'btn_retry': 'WIEDERHOLEN',
      'overlay_victory': 'LEVEL GESCHAFFT!',
      'overlay_victory_congrats': 'Glückwunsch! Alle Zielobjekte wurden gematcht.',
      'overlay_victory_daily': 'EVENT ABGESCHLOSSEN!',
      'overlay_victory_daily_congrats': 'Sie haben die heutige Sonderherausforderung abgeschlossen!',
      'btn_next_level': 'NÄCHSTES LEVEL',
      'btn_main_menu': 'HAUPTMENÜ',
      'settings_title': 'EINSTELLUNGEN',
      'settings_language': 'SPRACHE WÄHLEN',
      'settings_reset': 'KAMPAGNENFORTSCHRITT ZURÜCKSETZEN',
      'settings_close': 'SCHLIESSEN',
      'settings_reset_confirm': 'Fortschritt zurückgesetzt',
      'queue_next_up': 'ALS NÄCHSTES',
      'queue_tap_to_swap': 'ALS NÄCHSTES • ZUM TAUSCHEN TIPPEN',
      'tutorial_step1_title': 'TUTORIAL: GEWINNEN',
      'tutorial_step1_msg': 'Tippe auf das mittlere Feld, um die rote Kugel zu platzieren. Verbinde 3 in einer Linie, um ein Match zu erstellen!',
      'tutorial_step2_title': 'TUTORIAL: TAUSCHEN',
      'tutorial_step2_msg': 'Um das grüne Ziel zu erreichen, benötigst du eine grüne Kugel. Tippe auf die grüne Kugel in der Warteschlange unten, um sie nach vorne zu tauschen!',
      'tutorial_step3_title': 'TUTORIAL: LETZTES ZIEL',
      'tutorial_step3_msg': 'Großartig! Tippe jetzt auf das mittlere Feld, um die grüne Kugel zu platzieren und das Level abzuschließen.',
      'tutorial_l5_step1_title': 'TUTORIAL: BOMBE ERZEUGEN',
      'tutorial_l5_step1_msg': 'Verbinde 4 Objekte auf einmal, um eine Bombe zu erzeugen. Tippe auf das markierte Feld, um die rote Kugel zu platzieren!',
      'tutorial_l5_step2_title': 'TUTORIAL: BOMBE ZÜNDEN',
      'tutorial_l5_step2_msg': 'Um die Bombe zu zünden, lösche eine beliebige angrenzende Farbe. Tippe auf das markierte Feld, um die blaue Kugel zu platzieren und die Bombe zu zünden!',
      'hud_daily_sub': 'Räume alle 4 Zielsterne auf dem heutigen Spielfeld ab',
      'hud_campaign_sub': 'Räume alle Zielsterne ab, um fortzufahren',
    },
    'uk': {
      'title_hexa_match': 'ГЕКСА МАТЧ',
      'subtitle_neon': 'ЯСКРАВИЙ НЕОНОВИЙ ТРИ-В-РЯД',
      'btn_start_game': 'ПОЧАТИ ГРУ',
      'menu_subtitle': 'ОБЕРІТЬ СВІЙ ВИКЛИК',
      'card_play_campaign': 'ГРАТИ РІВЕНЬ {level}',
      'hud_level_title': 'РІВЕНЬ {level}',
      'card_campaign_sub': 'Прогрес кампанії збережено на пристрої',
      'card_daily_event': 'ЩОДЕННА ПОДІЯ',
      'card_daily_sub': 'Унікальна форма поля • Оновлюється щодня',
      'badge_completed': 'ВИКОНАНО',
      'badge_new_challenge': 'НОВИЙ ВИКЛИК',
      'panel_stats': 'ВАША СТАТИСТИКА',
      'stat_best_score': 'РЕКОРД',
      'stat_levels_cleared': 'ПРОЙДЕНО РІВНІВ',
      'hud_score': 'Рахунок: {score}',
      'hud_targets': 'Цілі: {targets}',
      'badge_difficulty_easy': 'Легко',
      'badge_difficulty_normal': 'Нормально',
      'badge_difficulty_medium': 'Середній',
      'badge_difficulty_hard': 'Складно',
      'badge_difficulty_very_hard': 'Дуже складно',
      'overlay_game_over': 'ГРА ЗАКІНЧЕНА',
      'overlay_game_over_sub': 'Шестикутне поле повністю заповнене.',
      'stat_final_score': 'ОСТАТОЧНИЙ РАХУНОК',
      'stat_current_score': 'ПОТОЧНИЙ РАХУНОК',
      'btn_play_again': 'ГРАТИ ЗНОВУ',
      'btn_retry': 'СПРОБУВАТИ ЗНОВУ',
      'overlay_victory': 'РІВЕНЬ ПРОЙДЕНО!',
      'overlay_victory_congrats': 'Вітаємо! Всі цільові сфери зібрано.',
      'overlay_victory_daily': 'ПОДІЮ ЗАВЕРШЕНО!',
      'overlay_victory_daily_congrats': 'Ви завершили сьогоднішнє особливе завдання!',
      'btn_next_level': 'НАСТУПНИЙ РІВЕНЬ',
      'btn_main_menu': 'ГОЛОВНЕ МЕНЮ',
      'settings_title': 'НАЛАШТУВАННЯ',
      'settings_language': 'ОБЕРІТЬ МОВУ',
      'settings_reset': 'СКИНУТИ ПРОГРЕС КАМПАНІЇ',
      'settings_close': 'ЗАКРИТИ',
      'settings_reset_confirm': 'Прогрес скинуто',
      'queue_next_up': 'НАСТУПНИЙ',
      'queue_tap_to_swap': 'НАСТУПНИЙ • НАТИСНІТЬ ДЛЯ ОБМІНУ',
      'tutorial_step1_title': 'НАВЧАННЯ: ЗБІГ',
      'tutorial_step1_msg': 'Натисніть на центральну комірку, щоб розмістити червону сферу. З\'єднайте 3 в лінію для збігу!',
      'tutorial_step2_title': 'НАВЧАННЯ: ОБМІН',
      'tutorial_step2_msg': 'Щоб зібрати зелену ціль, потрібна зелена сфера. Натисніть на зелену сферу в черзі нижче, щоб обміняти її вперед!',
      'tutorial_step3_title': 'НАВЧАННЯ: ОСТАННЯ ЦІЛЬ',
      'tutorial_step3_msg': 'Чудово! Тепер натисніть на центральну комірку, щоб розмістити зелену сферу та завершити рівень.',
      'tutorial_l5_step1_title': 'НАВЧАННЯ: СТВОРЕННЯ БОМБИ',
      'tutorial_l5_step1_msg': 'З\'єднайте 4 елементи одночасно, щоб створити бомбу. Натисніть на виділену комірку, щоб розмістити червону сферу!',
      'tutorial_l5_step2_title': 'НАВЧАННЯ: ДЕТОНАЦІЯ БОМБИ',
      'tutorial_l5_step2_msg': 'Щоб активувати бомбу, приберіть будь-який колір поруч. Натисніть на виділену комірку, щоб розмістити синю сферу та підірвати бомбу!',
      'hud_daily_sub': 'Зберіть всі 4 цільові зірки на сьогоднішньому полі',
      'hud_campaign_sub': 'Зберіть всі цільові зірки, щоб продовжити',
    },
  };

  /// Translate a given key in the active language.
  /// Supports dynamic argument replacement (e.g. {level}).
  static String translate(String key, String langCode, {Map<String, String>? args}) {
    // Fallback to English if language code is not found or unsupported
    final Map<String, String> translations = _localizedValues[langCode] ?? _localizedValues['en']!;
    
    // Fallback to key itself if key is not found
    String value = translations[key] ?? key;

    if (args != null && args.isNotEmpty) {
      args.forEach((argKey, argValue) {
        value = value.replaceAll('{$argKey}', argValue);
      });
    }

    return value;
  }
}
